import SideBar from '@/components/Layout/side-bar/side-bar'
import './globals.css'
import type { Metadata } from 'next'

import styles from './page.module.css'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body  className={styles.home}> <SideBar />{children}</body>
    </html>
  )
}
